package bitManipulation;

// Maximum AND Value
public class Task9 {

    // Given an array arr[] of N positive elements.
    // The task is to find the Maximum AND Value generated by
    // any pair(arr[i], arr[j]) from the array such that i != j.
    // Note: AND is bitwise '&' operator.

    public static void main(String[] args) {
        int[] arr = {4, 8, 12, 16};
        System.out.println(maxAND(arr, arr.length));
    }

    private static int maxAND(int[] arr, int n) {
        int res = 0;
        for (int i = 0; i < n; i++)
            for (int j = i + 1; j < n; j++)
                res = Math.max(res, (arr[i] & arr[j]));
        return res;
    }
}
